import textwrap

class MockLLM:
    """
    Simulates an LLM backend (like GPT-4 or Claude 3.5 Sonnet) used by Cursor.
    In a real implementation, this would make HTTP requests to an API.
    """
    
    def generate_edit(self, code_context: str, instruction: str) -> str:
        """
        Simulates the "Cmd+K" behavior: Takes code and instruction, returns modified code.
        """
        print(f"\n[AI Engine] Received instruction: '{instruction}'")
        print(f"[AI Engine] Analyzing {len(code_context)} bytes of code...")
        
        # Simple heuristics to simulate AI understanding for the demo
        if "docstring" in instruction.lower() or "comment" in instruction.lower():
            return self._add_docstrings(code_context)
        elif "type" in instruction.lower():
            return self._add_type_hints(code_context)
        elif "refactor" in instruction.lower():
            return self._refactor_code(code_context)
        else:
            # Default: Just append a comment showing it was processed
            return f"# AI: I processed this with instruction: {instruction}\n{code_context}"

    def _add_docstrings(self, code: str) -> str:
        lines = code.split('\n')
        new_lines = []
        for line in lines:
            new_lines.append(line)
            if "def " in line and ":" in line:
                indent = len(line) - len(line.lstrip())
                indent_str = " " * (indent + 4)
                new_lines.append(f'{indent_str}"""\n{indent_str}Generated by Mini-Cursor AI.\n{indent_str}"""')
        return "\n".join(new_lines)

    def _add_type_hints(self, code: str) -> str:
        # A very naive simulation of adding type hints
        code = code.replace("def greet(name):", "def greet(name: str) -> None:")
        return code

    def _refactor_code(self, code: str) -> str:
        return f"# Refactored Version\n{code}\n# End of Refactoring"
